### ISSUE TITLE
Graphite metrics with authentication

### ISSUE THREAD

**Issue by trhumphries** [ahdde/graphite.net#31]
How do I pass an authentication header in the request?

**Comment by tkirill** [comment]
What is the status of this issue? I also need this feature. I need to pass `Authorization` header to access Graphite. Ability to pass arbitrary default HTTP headers will be sufficient for this.

**Comment by zivillian** [comment]
you can pass an

**Comment by zivillian** [comment]
Wiht the latest version, you can pass a preconfigured HttpClient which contains the required HTTP headers.

**Comment by tkirill** [comment]
Yes, I've just upgraded to v3 and it works like a charm. Thanks!
