### ISSUE TITLE
Support for tz parameter in Render API

### ISSUE THREAD

**Issue by tkirill** [ahdde/graphite.net#36]
Hi!

What do you think about supporting [tz](https://graphite.readthedocs.io/en/latest/render_api.html#tz) parameter for Render API?

**Comment by zivillian** [comment]
Great idea, but it might take some time. If you are up for it, just create a PR.

**Comment by tkirill** [comment]
@zivillian I tried to implement this. See linked PR.

**Comment by zivillian** [comment]
@tkirill we've published a [beta release to nuget](https://www.nuget.org/packages/ahd.Graphite/3.1.0-beta-202304031)
